### ISSUE TITLE
Update about the ToDo stuff

### ISSUE THREAD

**Issue by jeamick** [solana-labs/network_simulation#1]
Hello Team,

I was wondering if someone is currently working on these stuff from the Readme : 

   - Lockout function tuning
   - Node BlockTransmission cache
   - Node save/tick/vote logic
   - Node stakes
   - Destaking/leakage
   - E&M

Thanks
JM

**Comment by ericlwilliams** [comment]
Hi @jeamick, this simulation work is pretty much deprecated as we're starting to explore most of this in tests on the actual network (see [here](https://github.com/solana-labs/solana/blob/master/tests/fork-selection.rs)). Most reliable TODO would be found under the upcoming beacons release [issues](https://github.com/solana-labs/solana/milestone/20), or if you're interested, feel free to find me on [discord](https://discord.gg/rAyHett) and I can catch you up on some of the economic work underway

**Comment by jeamick** [comment]
Thanks @ericlwilliams  I'll go on Discord then thanks
